development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: railstutorial
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: railstutorial
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: railstutorial
  password:

cucumber:
  <<: *test